app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix'=>'admin'], function () {
    Route::resource('cate', 'CateController');
    Route::resource('product', 'ProductController');

});
Route::get('', 'HomeController@index');
Route::get('/products', 'HomeController@search')->name('search');
Route::get('{cate}.html', 'HomeController@cate')->name('cate');
Route::get('{cate}/{product}-{id}.html', 'HomeController@detail')->name('detail')->where('product','[\w-]+');

app/Cate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cate extends Model
{
    protected $guarded = [];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CateController.php
<?php

namespace App\Http\Controllers;
use App\Cate;
use App\Http\Requests\CateAddRequest;
use Illuminate\Http\Request;

class CateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cates = Cate::paginate(10);

        return view('admin.cate.index',compact('cates'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cates = Cate::all();
        return view('admin.cate.create',compact('cates'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CateAddRequest $request)
    {
        $data = $request->all();
        $data['alias'] = str_slug($data['title']);
        Cate::create($data);
        return redirect('admin/cate')->with(['msg'=>'them thanh cong']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cates = Cate::where('id','<>',$id)->get();
        $cate = Cate::find($id);
        return view('admin.cate.edit',compact('cates','cate'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $data['alias'] = str_slug($data['title']);

        Cate::find($id)->update($data);
        return redirect('admin/cate')->with(['msg'=>'edit thanh cong']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Cate::find($id)->delete();
        return redirect('admin/cate')->with(['msg'=>'xoa thanh cong']);

    }
}

resources/views/admin/cate/create.blade.php
@extends('admin.master')
@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Quick Example</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="{{route('admin.cate.store')}}">
            {{ csrf_field() }}
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="name" class="form-control" id="exampleInputEmail1" placeholder="Enter name" name="title">
                    <span class="help-block">{{$errors->first('title')}}</span>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Parent id</label>
                    <select name="parent_id" id="" class="form-control">
                        <option value="0">Root</option>
                        @foreach($cates as $cate)
                        <option value="{{$cate->id}}">{{$cate->title}}</option>
                        @endforeach
                    </select>
                    <span class="help-block">{{$errors->first('parent_id')}}</span>

                </div>


            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@stop

resources/views/admin/cate/edit.blade.php
@extends('admin.master')
@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Quick Example</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="{{route('admin.cate.update',$cate->id)}}">
            {{ csrf_field() }}
            {{method_field('put')}}
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="name" value="{{$cate->title}}" class="form-control" id="exampleInputEmail1" placeholder="Enter name" name="title">
                    <span class="help-block">{{$errors->first('title')}}</span>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Parent id</label>
                    <select name="parent_id" id="" class="form-control">
                        <option value="0">Root</option>
                        @foreach($cates as $value)
                            @if($value->id==$cate->parent_id)
                                <option value="{{$value->id}}" selected>{{$value->title}}</option>
                            @else
                                <option value="{{$value->id}}">{{$value->title}}</option>
                            @endif
                        @endforeach
                    </select>
                    <span class="help-block">{{$errors->first('parent_id')}}</span>

                </div>


            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@stop

resources/views/admin/cate/index.blade.php
@extends('admin.master')
@section('content')
    <section class="content-header">
        <h1>
            Simple Tables
            <small>preview of simple tables</small>
        </h1>

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Simple</li>
        </ol>

    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Category List</h3>
                            <a href="{{route('admin.cate.create')}}" class="btn btn-success">Add Category</a>
                    </div>
                    @if(session('msg'))

                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{session('msg')}}!</h4>
                    </div>
                    @endif
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-bordered table-hover">
                            <tr>
                                <th style="width: 10px">STT</th>
                                <th>Tên</th>
                                <th>Danh mục cha</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            @forelse($cates as $cate)
                            <tr>
                                <td>{{$cate->id}}</td>
                                <td>{{$cate->title}}</td>
                                <td>
                                        @if($cate->parent_id!=0)
                                            {{\App\Cate::find($cate->parent_id)->title}}
                                         @else
                                            {{'thu muc goc'}}
                                        @endif
                                </td>
                                <td>
                                    <a href="{{route('admin.cate.edit',$cate->id)}}" class="btn btn-primary"
                                    >Edit</a>
                                </td>
                                <td>
                                    <form action="{{route('admin.cate.destroy',$cate->id)}}" method="post" id="delete{{$cate->id}}">
                                        {{ csrf_field() }}
                                        {{method_field('delete')}}
                                    </form>
                                    <a href="#" class="btn btn-danger"
                                    onclick="document.getElementById('delete{{$cate->id}}').submit()"
                                    >Delete</a>
                                </td>
                            </tr>
                                @empty
                                <tr>
                                    <td colspan="5">Chua co danh muc nao</td>
                                </tr>
                            @endforelse



                        </table>
                    </div>
                    <!-- /.box-body -->
                    {{--<div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            <li><a href="#">&laquo;</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>--}}
                    {{ $cates->links() }}
                </div>
                <!-- /.box -->


                <!-- /.box -->
            </div>
            <!-- /.col -->

            <!-- /.col -->
        </div>
        <!-- /.row -->

    </section>

@stop