app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix'=>'admin'], function () {
    Route::resource('cate', 'CateController');
    Route::resource('product', 'ProductController');

});
Route::get('', 'HomeController@index');
Route::get('/products', 'HomeController@search')->name('search');
Route::get('{cate}.html', 'HomeController@cate')->name('cate');
Route::get('{cate}/{product}-{id}.html', 'HomeController@detail')->name('detail')->where('product','[\w-]+');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = ['alias'];
    public function cate()
    {
        return $this->belongsTo(Cate::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductAddRequest;
use App\Product;
use App\Cate;

use Illuminate\Http\Request;

use App\Http\Requests;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);

        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cates = Cate::all();


        return view('admin.product.create',compact('cates'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductAddRequest $request)
    {
        $data = $request->all();
        if ($request->hasFile('image')) {
            $file = $request->file('image');

            $file->move('uploads',$file->getClientOriginalName());
            $data['image'] = $file->getClientOriginalName();
        }

        Product::create($data);
        return redirect()->route('admin.product.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $cates = Cate::all();


        return view('admin.product.edit',compact('product','cates'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\ProductEditRequest $request, $id)
    {
        $data = $request->all();
        if ($request->hasFile('image')) {
            $file = $request->file('image');

            $file->move('uploads',$file->getClientOriginalName());
            $data['image'] = $file->getClientOriginalName();
        }

        Product::find($id)->update($data);
        return redirect()->route('admin.product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect('admin/product')->with(['msg'=>'xoa thanh cong']);
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.master')
@section('content')
    <link rel="stylesheet" href="{{asset('adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Quick Example</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="{{route('admin.product.store')}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Title</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter name" name="title">
                    <span class="help-block">{{$errors->first('title')}}</span>

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Price</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter price" name="price">
                    <span class="help-block">{{$errors->first('price')}}</span>

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Image</label>
                    <input type="file" class="form-control" id="exampleInputEmail1" placeholder="Enter price" name="image">
                    <span class="help-block">{{$errors->first('image')}}</span>

                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">category</label>
                    <select name="cate_id" id="" class="form-control">
                        @foreach($cates as $cate)
                            <option value="{{$cate->id}}">{{$cate->title}}</option>
                        @endforeach
                    </select>
                    <span class="help-block">{{$errors->first('cate_id')}}</span>

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Content</label>
                    <textarea name="content" id="editor1" cols="30" rows="10" class="form-control textarea"></textarea>
                    <span class="help-block">{{$errors->first('content')}}</span>

                </div>


            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    <script src="{{asset('adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
    <script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1')
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>
@stop

resources/views/admin/product/edit.blade.php
@extends('admin.master')
@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Quick Example</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="{{route('admin.product.update',$product->id)}}">
            {{ csrf_field() }}
            {{method_field('put')}}
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Title</label>
                    <input type="text" value="{{$product->title}}" class="form-control" id="exampleInputEmail1" placeholder="Enter name" name="title">
                    <span class="help-block">{{$errors->first('title')}}</span>

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Price</label>
                    <input type="text"  value="{{$product->price}}"class="form-control" id="exampleInputEmail1" placeholder="Enter price" name="price">
                    <span class="help-block">{{$errors->first('price')}}</span>

                </div>
                <div class="form-group">
                    <img src="{{asset("uploads/$product->image")}}" alt="" width="100">
                    <label for="exampleInputEmail1">Image</label>
                    <input type="file" class="form-control" id="exampleInputEmail1" placeholder="Enter price" name="image">
                    <span class="help-block">{{$errors->first('image')}}</span>

                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">category</label>
                    <select name="cate_id" id="" class="form-control">
                        @foreach($cates as $value)
                            @if($value->id==$product->cate_id)
                                <option value="{{$value->id}}" selected>{{$value->title}}</option>
                            @else
                                <option value="{{$value->id}}">{{$value->title}}</option>
                            @endif
                        @endforeach
                    </select>
                    <span class="help-block">{{$errors->first('cate_id')}}</span>

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Content</label>
                    <textarea name="content" id="editor1" cols="30" rows="10" class="form-control textarea">{{$product->content}}</textarea>
                    <span class="help-block">{{$errors->first('content')}}</span>

                </div>


            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@stop

resources/views/admin/product/index.blade.php
@extends('admin.master')
@section('content')
    <section class="content-header">
        <h1>
            Simple Tables
            <small>preview of simple tables</small>
        </h1>

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Simple</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">List Products</h3>
                            <a href="{{route('admin.product.create')}}" class="btn btn-success">Add Product</a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-bordered">
                            <tr>
                                <th style="width: 10px">STT</th>
                                <th>Tên</th>
                                <th>image</th>
                                <th>Price</th>
                                <th>category</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            @forelse($products as $product)
                            <tr>
                                <td>{{$product->id}}</td>
                                <td>{{$product->title}}</td>
                                <td>
                                    <img src="{{asset("uploads/$product->image")}}" alt="" width="100">
                                </td>
                                <td>{{$product->price}}</td>
                                <td>
                                    {{$product->cate->title}}
                                </td>
                                <td>
                                    <a href="{{route('admin.product.edit',$product->id)}}" class="btn btn-primary"
                                    >Edit</a>
                                </td>
                                <td>
                                    <form action="{{route('admin.product.destroy',$product->id)}}" method="post" id="delete{{$product->id}}">
                                        {{ csrf_field() }}
                                        {{method_field('delete')}}
                                    </form>
                                    <a href="#" class="btn btn-danger"
                                       onclick="document.getElementById('delete{{$product->id}}').submit()"
                                    >Delete</a>
                                </td>
                            </tr>
                                @empty
                                <tr>
                                    <td colspan="7">chua co san pham nao</td>
                                </tr>
                            @endforelse



                        </table>
                    </div>
                    <!-- /.box-body -->
                    {{ $products->links() }}

                </div>
                <!-- /.box -->


                <!-- /.box -->
            </div>
            <!-- /.col -->

            <!-- /.col -->
        </div>
        <!-- /.row -->

    </section>

@stop